apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-configmap
data:
#   config.json: |
#     {
#       "api": "{{- printf "%s" .Values.frontend.api.url}}";
#     }
  config.json: |
    // https://profinit.eu/en/blog/build-once-deploy-many-in-react-dynamic-configuration-properties/
    const apiUrl = "{{- printf "%s" .Values.frontend.api.url}}";
    const env = "TEST";

  nginx.conf: |
    server {
        listen 8080;
        gzip on;
        gzip_http_version 1.1;
        gzip_disable      "MSIE [1-6]\.";
        gzip_min_length   1100;
        gzip_vary         on;
        gzip_proxied      expired no-cache no-store private auth;
        gzip_types        text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;
        gzip_comp_level   5;
        error_log /var/log/nginx/error.log;
        access_log /var/log/nginx/access.log;
        root /usr/share/nginx/html;
        location / {
            index index.html index.htm;
            try_files $uri $uri/ /index.html =404;
        }
    }
